name: Deploy Next.js site to Pages

on:
  push:
    branches: ["master"]
    
jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
         
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: ${{ steps.detect-package-manager.outputs.manager }}
          
      - name: Detect package manager
        id: detect-package-manager
        run: |
         npm install
      - name: Build
        run: |
         npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./out  
 
      - name: deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
            username: ${{ secrets.FTP_USERNAME }}
            server: ${{ secrets.FTP_SERVER }}
            ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: ${{ secrets.FTP_PORT }}
            sftp_only: true
            password: ${{ secrets.FTP_PASSWORD }}
            local_path: './out/*'
            remote_path: '/var/www/html/property'
            sftpArgs: '-o ConnectTimeout=5'
